version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Build and Run Container
          command: |
            set -x
            docker-compose pull

      - run:
          name: Run Tests
          command: |
            set -x
            docker-compose run compute-box pytest -v