version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Pull Docker Image
          command: |
            set -x
            docker-compose --file docker-compose-cpu.yml pull

      - run:
          name: Run Tests
          command: |
            set -x
            docker-compose --file docker-compose-cpu.yml run compute-box-cpu pytest -v