version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Pull Docker Image
          command: |
            set -x
            docker-compose pull

      - run:
          name: Run Tests
          command: |
            set -x
            docker-compose run -e PATH=/opt/anaconda/envs/icc-cpu/bin:$PYTHONPATH:$PATH compute-box pytest -v